In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



df = pd.read_csv('../data/dataset_2021-5-26-10-14.csv', sep='\t', encoding='utf-8')

In [3]:
df.head()

,default_3months,ioi_36months,ioi_3months,valor_por_vencer,valor_vencido,valor_quitado,quant_protestos,valor_protestos,quant_acao_judicial,acao_judicial_valor,...,dividas_vencidas_qtd,falencia_concordata_qtd,tipo_sociedade,opcao_tributaria,atividade_principal,forma_pagamento,valor_total_pedido,month,year,default
0,0,58.000000,18.236092,0.00,0.0,242100.70,0,0.0,0,0.0,...,0,0,empresario (individual),simples nacional,papelaria,30/60/90,34665.674938,6,2019,0
1,1,16.052632,7.500000,224132.85,0.0,4960846.21,0,0.0,0,0.0,...,0,0,sociedade empresaria limitada,missing,com de equipamentos de informatica,30/60/90,7134.489373,10,2018,0
2,0,13.250000,3.904762,513043.83,0.0,158631.93,1,1800.0,0,0.0,...,0,0,sociedade empresaria limitada,simples nacional,servicos de vigilancia e guarda,missing,72653.621143,4,2018,0
3,0,136.925000,10.144219,23273.64,0.0,669644.16,0,0.0,0,0.0,...,0,0,empresario (individual),simples nacional,com de equipamentos de informatica,missing,14576.805783,4,2017,1
4,0,140.333333,17.651678,0.00,0.0,2010.56,0,0.0,0,0.0,...,0,0,sociedade empresaria limitada,simples nacional,com de compon eletron e pecas para eletrod,30/60/90,2655.505663,10,2017,0

In [4]:
df.shape

(117273, 22)

In [5]:
df.describe()

,default_3months,ioi_36months,ioi_3months,valor_por_vencer,valor_vencido,valor_quitado,quant_protestos,valor_protestos,quant_acao_judicial,acao_judicial_valor,participacao_falencia_valor,dividas_vencidas_valor,dividas_vencidas_qtd,falencia_concordata_qtd,valor_total_pedido,month,year,default
count,117273.000000,117273.000000,117273.000000,1.172730e+05,1.172730e+05,1.172730e+05,117273.000000,1.172730e+05,117273.000000,1.172730e+05,117273.0,1.172730e+05,117273.000000,117273.000000,1.172730e+05,117273.000000,117273.000000,117273.000000
mean,0.148721,55.582906,17.106291,6.421384e+04,2.454043e+03,1.085557e+06,0.240456,2.051017e+03,0.018922,9.218511e+02,0.0,5.603808e+02,0.014974,0.000622,2.406180e+04,6.279169,2017.976798,0.166662
std,0.853794,60.989240,10.993605,5.252546e+05,8.093313e+04,7.444825e+06,10.707825,8.831758e+04,0.534034,4.861025e+04,0.0,8.459291e+04,0.397264,0.030759,4.906680e+05,3.194997,0.742185,0.372676
min,0.000000,1.000000,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000,-7.446899e+02,1.000000,2017.000000,0.000000
25%,0.000000,20.166667,11.121543,5.657400e+02,0.000000e+00,1.944250e+04,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000,2.140419e+03,3.000000,2017.000000,0.000000
50%,0.000000,38.000000,16.000000,4.451740e+03,0.000000e+00,8.134878e+04,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000,4.012731e+03,7.000000,2018.000000,0.000000
75%,0.000000,69.750000,18.248850,2.006296e+04,0.000000e+00,3.322643e+05,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000,0.000000,9.645923e+03,9.000000,2019.000000,0.000000
max,26.000000,951.000000,90.000000,7.219759e+07,1.315050e+07,4.603203e+08,2324.000000,1.630546e+07,80.000000,8.390986e+06,0.0,1.972251e+07,40.000000,2.000000,1.503340e+08,12.000000,2019.000000,1.000000

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 117273 entries, 0 to 117272
Data columns (total 22 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   default_3months              117273 non-null  int64
 1   ioi_36months                 117273 non-null  float64
 2   ioi_3months                  117273 non-null  float64
 3   valor_por_vencer             117273 non-null  float64
 4   valor_vencido                117273 non-null  float64
 5   valor_quitado                117273 non-null  float64
 6   quant_protestos              117273 non-null  int64
 7   valor_protestos              117273 non-null  float64
 8   quant_acao_judicial          117273 non-null  int64
 9   acao_judicial_valor          117273 non-null  float64
 10  participacao_falencia_valor  117273 non-null  float64
 11  dividas_vencidas_valor       117273 non-null  float64
 12  dividas_vencidas_qtd         117273 non-null  int64
 13  falencia_concordata_qtd      117273 non-null  int64
 14  tipo_sociedade               117273 non-null  str
 15  opcao_tributaria             117273 non-null  str
 16  atividade_principal          117273 non-null  str
 17  forma_pagamento              117273 non-null  str
 18  valor_total_pedido           117273 non-null  float64
 19  month                        117273 non-null  int64
 20  year                         117273 non-null  int64
 21  default                      117273 non-null  int64
dtypes: float64(10), int64(8), str(4)
memory usage: 19.7 MB

In [15]:
df = df.replace('missing', np.nan)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 117273 entries, 0 to 117272
Data columns (total 22 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   default_3months              117273 non-null  int64
 1   ioi_36months                 117273 non-null  float64
 2   ioi_3months                  117273 non-null  float64
 3   valor_por_vencer             117273 non-null  float64
 4   valor_vencido                117273 non-null  float64
 5   valor_quitado                117273 non-null  float64
 6   quant_protestos              117273 non-null  int64
 7   valor_protestos              117273 non-null  float64
 8   quant_acao_judicial          117273 non-null  int64
 9   acao_judicial_valor          117273 non-null  float64
 10  participacao_falencia_valor  117273 non-null  float64
 11  dividas_vencidas_valor       117273 non-null  float64
 12  dividas_vencidas_qtd         117273 non-null  int64
 13  falencia_concordata_qtd      117273 non-null  int64
 14  tipo_sociedade               116665 non-null  str
 15  opcao_tributaria             98948 non-null   str
 16  atividade_principal          116681 non-null  str
 17  forma_pagamento              84796 non-null   str
 18  valor_total_pedido           117273 non-null  float64
 19  month                        117273 non-null  int64
 20  year                         117273 non-null  int64
 21  default                      117273 non-null  int64
dtypes: float64(10), int64(8), str(4)
memory usage: 19.7 MB

In [18]:
df.isnull().sum()

default_3months                    0
ioi_36months                       0
ioi_3months                        0
valor_por_vencer                   0
valor_vencido                      0
valor_quitado                      0
quant_protestos                    0
valor_protestos                    0
quant_acao_judicial                0
acao_judicial_valor                0
participacao_falencia_valor        0
dividas_vencidas_valor             0
dividas_vencidas_qtd               0
falencia_concordata_qtd            0
tipo_sociedade                   608
opcao_tributaria               18325
atividade_principal              592
forma_pagamento                32477
valor_total_pedido                 0
month                              0
year                               0
default                            0
dtype: int64